services:
  traefik:
    image: docker.io/traefik:v3.6@sha256:9004e1cd1e33c5eb0b6ec02bc6cfda61fe9caca36751114b1c9c6662f01b264a
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=bridge"
      - "--entrypoints.web.address=:80"
    ports:
      - target: 80
        published: 8000
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - "/run/user/${UID}/docker.sock:/var/run/docker.sock"
    networks:
      - bridge-net
    deploy:
      container_labels:
        - "traefik.enable=true"
        - "traefik.docker.network=bridge"
        - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
        - "traefik.http.routers.api.service=api@internal"

networks:
  bridge-net:
    external: true
    name: bridge
